#!/bin/sh
while true
do
	#MEMORY=$(free -m | /usr/bin/grep Mem | awk '{print "("$3"/"$2")"}')
	NETWORK=$(iwgetid -r)
	VOLUME=$(pamixer --get-volume)
	BRIGHTNESS=$(xbacklight -get)
	CHARGE="$(cat /sys/class/power_supply/BAT0/capacity)%"
	[ "$(cat /sys/class/power_supply/BAT0/status)" == "Charging" ] && CHARGE="${CHARGE}C"
	DATE=$(date "+%m-%d - %H:%M")
	
	STATUS="[NET: $NETWORK] [VOL: $VOLUME%] [BRT: $BRIGHTNESS%] [BATT: $CHARGE] [$DATE]"
	xsetroot -name "$STATUS"
	sleep 10
done
