#!/bin/sh

# If grepped success, it is not keymapped to ezmod
grepped=$(xmodmap -pke | grep 'eycode  64 = Mode_switch')

# Easy mod
if [ ! -z "$grepped" ]; then
    # Reset key mapping
    setxkbmap -option && killall dstatus
else
    # Enable ezkeymap
    xmodmap ~/.Xmodmap && killall dstatus
fi

dstatus & disown
exit 0
