#!/bin/bash
# Give arugment 0 to turn off touchpad and 1 to turn on touchpad

if [ "$#" = "0" ]; then
    ID=$(xinput --list --short | awk -F"\t" '/TouchPad/{print $2}' | cut -d'=' -f 2 )
	STATE=$(xinput list-props $ID | grep 'Device Enabled' | awk '{print $4}')
	case $STATE in
		1)
    		xinput set-prop $ID "Device Enabled" 0
			;;
		0)
    		xinput set-prop $ID "Device Enabled" 1
			;;
	esac
	exit 0
fi

if [ "$1" != "1" ] && [ "$1" != "0" ]; then
    echo "Valid argument => [0 OR 1]"
else 
    # Find the Id of Touchpad id from xinput list.
    id=$(xinput --list --short | awk -F"\t" '/TouchPad/{print $2}' | cut -d'=' -f 2 )

    #For Debug
    #echo $id 

    xinput set-prop $id "Device Enabled" $1
fi
