#!/bin/bash

inp="dir_home\ndir_prog\ndir_latex\ndir_doc\ndir_unity\ndis_task\nbin_rtop\nbin_htop\nbin_gt\nshl_update"
destination=("/home/$USER/" "/home/$USER/programming/" "/home/$USER/Unity/Projects")

result=$(echo -e "$inp" | dmenu -i -p "Exec")
case $result in
	"dir_home")
		alacritty -e ranger ${destination[0]}
		;;
	"dir_prog")
		alacritty -e ranger ${destination[1]}
		;;
	"dir_latex")
		alacritty -e ranger /home/simon/latex/
		;;
	"dir_doc")
		alacritty -e ranger /home/$USER/문서
		;;
	"dir_unity")
		alacritty -e ranger ${destination[2]}
		;;
	"dis_task")
		alacritty -e dtask
		;;
	"bin_rtop")
		alacritty -e radeontop
		;;
	"bin_htop")
		alacritty -e htop
		;;
	"bin_gt")
		alacritty -e gt
		;;
	"shl_update")
		alacritty -e dupdate
		;;
esac
